AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CodePipelineBucket:
    Type: String
    Description: "S3 Bucket for CodePipeline artifacts."

Resources:
  CodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    # <add resource-specific properties underneath this entry  - available properties are listed in code completion>
    Properties:
      BucketName: !Ref CodePipelineBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
